/*
 * Click nargs://.netbeans/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nargs://.netbeans/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.monster.vista;

import ec.edu.monster.controlador.AppControlador;
import javax.swing.*;
import java.awt.*;
import javax.swing.border.LineBorder;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author MATIAS
 */
public class LoginVista extends javax.swing.JFrame {

    /**
     * Creates new form LoginVista
     */
    private AppControlador controlador;

    public LoginVista() {
        initComponents();
        this.setLocationRelativeTo(null);
        controlador = new AppControlador();
        // Habilitar maximización y cierre
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Maximizar por defecto
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold desc="Generated Code">
    private void initComponents() {

        // Declarar componentes como variables de instancia
        txtUsuario = new JTextField();
        txtContraseña = new JPasswordField();
        btnIniciarSesión = new JButton();

        // Panel de encabezado
        JPanel headerPanel = new JPanel();
        headerPanel.setBackground(new Color(0x46535d));
        headerPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 20, 10));
        headerPanel.setPreferredSize(new Dimension(0, 50)); // Altura fija, ancho adaptable

        JLabel headerLabel = new JLabel("Inicio de sesión");
        headerLabel.setFont(new Font("Segoe UI", Font.BOLD, 18));
        headerLabel.setForeground(Color.WHITE);
        headerPanel.add(headerLabel);

        // Panel contenedor principal con márgenes
        JPanel containerPanel = new JPanel(new BorderLayout());
        containerPanel.setBorder(new EmptyBorder(20, 20, 20, 20)); // Márgenes de 20px

        // Panel principal con padding interno
        JPanel mainPanel = new JPanel();
        mainPanel.setBackground(new Color(0xf6f7f6));
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setBorder(new EmptyBorder(20, 20, 20, 20)); // Padding interno
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.anchor = GridBagConstraints.CENTER;

        // Mensaje de bienvenida
        JLabel welcomeLabel = new JLabel("Bienvenido");
        welcomeLabel.setFont(new Font("Segoe UI", Font.BOLD, 24));
        welcomeLabel.setHorizontalAlignment(SwingConstants.CENTER);
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weightx = 0.0; // No expansión horizontal
        mainPanel.add(welcomeLabel, gbc);

        JLabel subtextLabel = new JLabel("Por favor, ingresa tus credenciales");
        subtextLabel.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        subtextLabel.setForeground(new Color(0x666666));
        subtextLabel.setHorizontalAlignment(SwingConstants.CENTER);
        gbc.gridy = 1;
        mainPanel.add(subtextLabel, gbc);

        // Imagen de avatar
        JLabel avatarLabel = new JLabel();
        try {
            ImageIcon avatarIcon = new ImageIcon(getClass().getResource("/images/sulley.png"));
            Image scaledImage = avatarIcon.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH); // Tamaño inicial
            avatarLabel.setIcon(new ImageIcon(scaledImage));
        } catch (Exception e) {
            avatarLabel.setText("(Avatar no disponible)");
        }
        avatarLabel.setHorizontalAlignment(SwingConstants.CENTER);
        gbc.gridy = 2;
        gbc.weightx = 0.0; // No expansión horizontal
        gbc.weighty = 0.0; // No expansión vertical
        mainPanel.add(avatarLabel, gbc);

        // Campo de usuario
        JLabel userLabel = new JLabel("Usuario");
        userLabel.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        gbc.gridy = 3;
        gbc.gridwidth = 1;
        gbc.weightx = 0.0;
        mainPanel.add(userLabel, gbc);

        txtUsuario.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        txtUsuario.setBorder(new LineBorder(new Color(0xb1c5c7), 1));
        txtUsuario.setPreferredSize(new Dimension(250, 30)); // Ancho inicial razonable
        txtUsuario.setMaximumSize(new Dimension(300, 30)); // Límite máximo de ancho
        txtUsuario.addActionListener(evt -> txtUsuarioActionPerformed(evt));
        gbc.gridy = 4;
        gbc.weightx = 0.0; // Sin expansión horizontal
        mainPanel.add(txtUsuario, gbc);

        // Campo de contraseña
        JLabel passwordLabel = new JLabel("Contraseña");
        passwordLabel.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        gbc.gridy = 5;
        gbc.weightx = 0.0;
        mainPanel.add(passwordLabel, gbc);

        txtContraseña.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        txtContraseña.setBorder(new LineBorder(new Color(0xb1c5c7), 1));
        txtContraseña.setPreferredSize(new Dimension(250, 30)); // Ancho inicial razonable
        txtContraseña.setMaximumSize(new Dimension(300, 30)); // Límite máximo de ancho
        txtContraseña.addActionListener(evt -> txtContraseñaActionPerformed(evt));
        gbc.gridy = 6;
        gbc.weightx = 0.0; // Sin expansión horizontal
        mainPanel.add(txtContraseña, gbc);

        // Botón de inicio de sesión
        btnIniciarSesión.setText("Iniciar Sesión");
        btnIniciarSesión.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btnIniciarSesión.setBackground(new Color(0x202224));
        btnIniciarSesión.setForeground(Color.WHITE);
        btnIniciarSesión.setPreferredSize(new Dimension(250, 40)); // Ancho inicial razonable
        btnIniciarSesión.setMaximumSize(new Dimension(300, 40)); // Límite máximo de ancho
        btnIniciarSesión.setFocusPainted(false);
        btnIniciarSesión.addActionListener(evt -> btnIniciarSesiónActionPerformed(evt));
        gbc.gridy = 7;
        gbc.weightx = 0.0; // Sin expansión horizontal
        mainPanel.add(btnIniciarSesión, gbc);

        // Añadir mainPanel al containerPanel
        containerPanel.add(mainPanel, BorderLayout.CENTER);

        // Configuración del marco
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de Sesión");
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(headerPanel, BorderLayout.NORTH);
        getContentPane().add(containerPanel, BorderLayout.CENTER);

        pack();
        // Ajustar tamaño mínimo para evitar que se colapse
        setMinimumSize(new Dimension(400, 500));
    }// </editor-fold>

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnIniciarSesiónActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            // Obtener los datos de entrada
            String user = txtUsuario.getText();
            String password = new String(txtContraseña.getPassword());

            // Validar que los campos no estén vacíos
            if (user.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Intentar iniciar sesión
            boolean success = controlador.login(user, password);

            if (success) {
                // Cerrar la ventana de login
                this.dispose();
                // Abrir la vista del conversor
                new CONUNIVista().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al iniciar sesión: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginVista().setVisible(true));
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnIniciarSesión;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JPasswordField txtContraseña;
    // End of variables declaration
}