package ec.edu.monster.ws;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-05-01T20:39:37.348-05:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://controlador.monster.edu.ec/", name = "CONUNI")
@XmlSeeAlso({ObjectFactory.class})
public interface CONUNI {

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/CONUNI/sumaRequest", output = "http://controlador.monster.edu.ec/CONUNI/sumaResponse")
    @RequestWrapper(localName = "suma", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.Suma")
    @ResponseWrapper(localName = "sumaResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.SumaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int suma(

        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b
    );

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/CONUNI/centimetrosAPulgadasRequest", output = "http://controlador.monster.edu.ec/CONUNI/centimetrosAPulgadasResponse")
    @RequestWrapper(localName = "centimetrosAPulgadas", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.CentimetrosAPulgadas")
    @ResponseWrapper(localName = "centimetrosAPulgadasResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.CentimetrosAPulgadasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double centimetrosAPulgadas(

        @WebParam(name = "centimetros", targetNamespace = "")
        double centimetros
    );

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/CONUNI/pulgadasACentimetrosRequest", output = "http://controlador.monster.edu.ec/CONUNI/pulgadasACentimetrosResponse")
    @RequestWrapper(localName = "pulgadasACentimetros", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.PulgadasACentimetros")
    @ResponseWrapper(localName = "pulgadasACentimetrosResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.PulgadasACentimetrosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double pulgadasACentimetros(

        @WebParam(name = "pulgadas", targetNamespace = "")
        double pulgadas
    );

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/CONUNI/loginRequest", output = "http://controlador.monster.edu.ec/CONUNI/loginResponse")
    @RequestWrapper(localName = "login", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.LoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean login(

        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "contraseña", targetNamespace = "")
        java.lang.String contraseña
    );
}
