
package ec.edu.monster.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-05-30T17:25:52.286-05:00
 * Generated source version: 4.0.3
 *
 */
public final class WSAerolineasCondor_WSAerolineasCondorPort_Client {

    private static final QName SERVICE_NAME = new QName("http://controlador.monster.edu.ec/", "WSAerolineasCondor");

    private WSAerolineasCondor_WSAerolineasCondorPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WSAerolineasCondor_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        WSAerolineasCondor_Service ss = new WSAerolineasCondor_Service(wsdlURL, SERVICE_NAME);
        WSAerolineasCondor port = ss.getWSAerolineasCondorPort();

        {
        System.out.println("Invoking buscarVuelos...");
        java.lang.String _buscarVuelos_ciudadOrigen = "";
        java.lang.String _buscarVuelos_ciudadDestino = "";
        javax.xml.datatype.XMLGregorianCalendar _buscarVuelos_fecha = null;
        java.util.List<ec.edu.monster.ws.Vuelo> _buscarVuelos__return = port.buscarVuelos(_buscarVuelos_ciudadOrigen, _buscarVuelos_ciudadDestino, _buscarVuelos_fecha);
        System.out.println("buscarVuelos.result=" + _buscarVuelos__return);


        }
        {
        System.out.println("Invoking iniciarSesion...");
        java.lang.String _iniciarSesion_nombreUsuario = "";
        java.lang.String _iniciarSesion_claveUsuario = "";
        ec.edu.monster.ws.Usuario _iniciarSesion__return = port.iniciarSesion(_iniciarSesion_nombreUsuario, _iniciarSesion_claveUsuario);
        System.out.println("iniciarSesion.result=" + _iniciarSesion__return);


        }
        {
        System.out.println("Invoking registrarCompra...");
        int _registrarCompra_idVuelo = 0;
        int _registrarCompra_idCliente = 0;
        int _registrarCompra__return = port.registrarCompra(_registrarCompra_idVuelo, _registrarCompra_idCliente);
        System.out.println("registrarCompra.result=" + _registrarCompra__return);


        }
        {
        System.out.println("Invoking obtenerVueloMasCaro...");
        java.lang.String _obtenerVueloMasCaro_ciudadOrigen = "";
        java.lang.String _obtenerVueloMasCaro_ciudadDestino = "";
        javax.xml.datatype.XMLGregorianCalendar _obtenerVueloMasCaro_fecha = null;
        ec.edu.monster.ws.Vuelo _obtenerVueloMasCaro__return = port.obtenerVueloMasCaro(_obtenerVueloMasCaro_ciudadOrigen, _obtenerVueloMasCaro_ciudadDestino, _obtenerVueloMasCaro_fecha);
        System.out.println("obtenerVueloMasCaro.result=" + _obtenerVueloMasCaro__return);


        }
        {
        System.out.println("Invoking obtenerComprasCliente...");
        int _obtenerComprasCliente_idCliente = 0;
        java.util.List<ec.edu.monster.ws.Compra> _obtenerComprasCliente__return = port.obtenerComprasCliente(_obtenerComprasCliente_idCliente);
        System.out.println("obtenerComprasCliente.result=" + _obtenerComprasCliente__return);


        }
        {
        System.out.println("Invoking registrarUsuario...");
        int _registrarUsuario_idCliente = 0;
        java.lang.String _registrarUsuario_nombreUsuario = "";
        java.lang.String _registrarUsuario_claveUsuario = "";
        ec.edu.monster.ws.Usuario _registrarUsuario__return = port.registrarUsuario(_registrarUsuario_idCliente, _registrarUsuario_nombreUsuario, _registrarUsuario_claveUsuario);
        System.out.println("registrarUsuario.result=" + _registrarUsuario__return);


        }
        {
        System.out.println("Invoking registrarCliente...");
        java.lang.String _registrarCliente_nombre = "";
        java.lang.String _registrarCliente_email = "";
        java.lang.String _registrarCliente_documentoIdentidad = "";
        ec.edu.monster.ws.Cliente _registrarCliente__return = port.registrarCliente(_registrarCliente_nombre, _registrarCliente_email, _registrarCliente_documentoIdentidad);
        System.out.println("registrarCliente.result=" + _registrarCliente__return);


        }

        System.exit(0);
    }

}
