package ec.edu.monster.ws;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-05-29T18:11:08.849-05:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://controlador.monster.edu.ec/", name = "WSAerolineasCondor")
@XmlSeeAlso({ObjectFactory.class})
public interface WSAerolineasCondor {

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/WSAerolineasCondor/buscarVuelosRequest", output = "http://controlador.monster.edu.ec/WSAerolineasCondor/buscarVuelosResponse")
    @RequestWrapper(localName = "buscarVuelos", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.BuscarVuelos")
    @ResponseWrapper(localName = "buscarVuelosResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.BuscarVuelosResponse")
    @WebResult(name = "Vuelo", targetNamespace = "")
    public java.util.List<ec.edu.monster.ws.Vuelo> buscarVuelos(

        @WebParam(name = "ciudadOrigen", targetNamespace = "")
        java.lang.String ciudadOrigen,
        @WebParam(name = "ciudadDestino", targetNamespace = "")
        java.lang.String ciudadDestino,
        @WebParam(name = "fecha", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar fecha
    );

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/WSAerolineasCondor/iniciarSesionRequest", output = "http://controlador.monster.edu.ec/WSAerolineasCondor/iniciarSesionResponse")
    @RequestWrapper(localName = "iniciarSesion", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.IniciarSesion")
    @ResponseWrapper(localName = "iniciarSesionResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.IniciarSesionResponse")
    @WebResult(name = "Usuario", targetNamespace = "")
    public ec.edu.monster.ws.Usuario iniciarSesion(

        @WebParam(name = "nombreUsuario", targetNamespace = "")
        java.lang.String nombreUsuario,
        @WebParam(name = "claveUsuario", targetNamespace = "")
        java.lang.String claveUsuario
    );

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/WSAerolineasCondor/registrarCompraRequest", output = "http://controlador.monster.edu.ec/WSAerolineasCondor/registrarCompraResponse")
    @RequestWrapper(localName = "registrarCompra", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.RegistrarCompra")
    @ResponseWrapper(localName = "registrarCompraResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.RegistrarCompraResponse")
    @WebResult(name = "estado", targetNamespace = "")
    public int registrarCompra(

        @WebParam(name = "idVuelo", targetNamespace = "")
        int idVuelo,
        @WebParam(name = "idCliente", targetNamespace = "")
        int idCliente
    );

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/WSAerolineasCondor/obtenerVueloMasCaroRequest", output = "http://controlador.monster.edu.ec/WSAerolineasCondor/obtenerVueloMasCaroResponse")
    @RequestWrapper(localName = "obtenerVueloMasCaro", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.ObtenerVueloMasCaro")
    @ResponseWrapper(localName = "obtenerVueloMasCaroResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.ObtenerVueloMasCaroResponse")
    @WebResult(name = "Vuelo", targetNamespace = "")
    public ec.edu.monster.ws.Vuelo obtenerVueloMasCaro(

        @WebParam(name = "ciudadOrigen", targetNamespace = "")
        java.lang.String ciudadOrigen,
        @WebParam(name = "ciudadDestino", targetNamespace = "")
        java.lang.String ciudadDestino,
        @WebParam(name = "fecha", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar fecha
    );

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/WSAerolineasCondor/obtenerComprasClienteRequest", output = "http://controlador.monster.edu.ec/WSAerolineasCondor/obtenerComprasClienteResponse")
    @RequestWrapper(localName = "obtenerComprasCliente", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.ObtenerComprasCliente")
    @ResponseWrapper(localName = "obtenerComprasClienteResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.ObtenerComprasClienteResponse")
    @WebResult(name = "Compra", targetNamespace = "")
    public java.util.List<ec.edu.monster.ws.Compra> obtenerComprasCliente(

        @WebParam(name = "idCliente", targetNamespace = "")
        int idCliente
    );

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/WSAerolineasCondor/registrarUsuarioRequest", output = "http://controlador.monster.edu.ec/WSAerolineasCondor/registrarUsuarioResponse")
    @RequestWrapper(localName = "registrarUsuario", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.RegistrarUsuario")
    @ResponseWrapper(localName = "registrarUsuarioResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.RegistrarUsuarioResponse")
    @WebResult(name = "Usuario", targetNamespace = "")
    public ec.edu.monster.ws.Usuario registrarUsuario(

        @WebParam(name = "idCliente", targetNamespace = "")
        int idCliente,
        @WebParam(name = "nombreUsuario", targetNamespace = "")
        java.lang.String nombreUsuario,
        @WebParam(name = "claveUsuario", targetNamespace = "")
        java.lang.String claveUsuario
    );

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/WSAerolineasCondor/registrarClienteRequest", output = "http://controlador.monster.edu.ec/WSAerolineasCondor/registrarClienteResponse")
    @RequestWrapper(localName = "registrarCliente", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.RegistrarCliente")
    @ResponseWrapper(localName = "registrarClienteResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.RegistrarClienteResponse")
    @WebResult(name = "Cliente", targetNamespace = "")
    public ec.edu.monster.ws.Cliente registrarCliente(

        @WebParam(name = "nombre", targetNamespace = "")
        java.lang.String nombre,
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email,
        @WebParam(name = "documentoIdentidad", targetNamespace = "")
        java.lang.String documentoIdentidad
    );
}
