package ec.edu.monster.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-05-30T17:25:52.392-05:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "WSAerolineasCondor",
                  wsdlLocation = "http://localhost:8080/VIAJECITOS_SOAP_GR10/WSAerolineasCondor?wsdl",
                  targetNamespace = "http://controlador.monster.edu.ec/")
public class WSAerolineasCondor_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://controlador.monster.edu.ec/", "WSAerolineasCondor");
    public final static QName WSAerolineasCondorPort = new QName("http://controlador.monster.edu.ec/", "WSAerolineasCondorPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/VIAJECITOS_SOAP_GR10/WSAerolineasCondor?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSAerolineasCondor_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/VIAJECITOS_SOAP_GR10/WSAerolineasCondor?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSAerolineasCondor_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSAerolineasCondor_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSAerolineasCondor_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WSAerolineasCondor_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WSAerolineasCondor_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WSAerolineasCondor_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WSAerolineasCondor
     */
    @WebEndpoint(name = "WSAerolineasCondorPort")
    public WSAerolineasCondor getWSAerolineasCondorPort() {
        return super.getPort(WSAerolineasCondorPort, WSAerolineasCondor.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSAerolineasCondor
     */
    @WebEndpoint(name = "WSAerolineasCondorPort")
    public WSAerolineasCondor getWSAerolineasCondorPort(WebServiceFeature... features) {
        return super.getPort(WSAerolineasCondorPort, WSAerolineasCondor.class, features);
    }

}
