package ec.edu.monster.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
 * 2025-05-14T11:47:42.133-05:00
=======
 * 2025-05-14T11:27:57.912-05:00
>>>>>>> 822890f65bf73e8532339c88aa949a0c8de99c6b
=======
 * 2025-05-14T11:27:57.912-05:00
>>>>>>> 822890f65bf73e8532339c88aa949a0c8de99c6b
=======
 * 2025-05-14T11:27:57.912-05:00
>>>>>>> 822890f65bf73e8532339c88aa949a0c8de99c6b
=======
 * 2025-05-14T11:27:57.912-05:00
>>>>>>> 822890f65bf73e8532339c88aa949a0c8de99c6b
=======
 * 2025-05-14T11:27:57.912-05:00
>>>>>>> 822890f65bf73e8532339c88aa949a0c8de99c6b
=======
 * 2025-05-14T11:27:57.912-05:00
>>>>>>> 822890f65bf73e8532339c88aa949a0c8de99c6b
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "CONUNI",
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
                  wsdlLocation = "http://10.40.28.227:8080/CONUNI_GR10/CONUNI?wsdl",
=======
                  wsdlLocation = "http://10.40.27.8:8080/CONUNI_GR10/CONUNI?wsdl",
>>>>>>> 822890f65bf73e8532339c88aa949a0c8de99c6b
=======
                  wsdlLocation = "http://10.40.27.8:8080/CONUNI_GR10/CONUNI?wsdl",
>>>>>>> 822890f65bf73e8532339c88aa949a0c8de99c6b
=======
                  wsdlLocation = "http://10.40.27.8:8080/CONUNI_GR10/CONUNI?wsdl",
>>>>>>> 822890f65bf73e8532339c88aa949a0c8de99c6b
=======
                  wsdlLocation = "http://10.40.27.8:8080/CONUNI_GR10/CONUNI?wsdl",
>>>>>>> 822890f65bf73e8532339c88aa949a0c8de99c6b
=======
                  wsdlLocation = "http://10.40.27.8:8080/CONUNI_GR10/CONUNI?wsdl",
>>>>>>> 822890f65bf73e8532339c88aa949a0c8de99c6b
=======
                  wsdlLocation = "http://10.40.27.8:8080/CONUNI_GR10/CONUNI?wsdl",
>>>>>>> 822890f65bf73e8532339c88aa949a0c8de99c6b
                  targetNamespace = "http://controlador.monster.edu.ec/")
public class CONUNI_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://controlador.monster.edu.ec/", "CONUNI");
    public final static QName CONUNIPort = new QName("http://controlador.monster.edu.ec/", "CONUNIPort");
    static {
        URL url = null;
        try {
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
            url = new URL("http://10.40.28.227:8080/CONUNI_GR10/CONUNI?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CONUNI_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://10.40.28.227:8080/CONUNI_GR10/CONUNI?wsdl");
=======
=======
>>>>>>> 822890f65bf73e8532339c88aa949a0c8de99c6b
            url = new URL("http://10.40.27.8:8080/CONUNI_GR10/CONUNI?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CONUNI_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://10.40.27.8:8080/CONUNI_GR10/CONUNI?wsdl");
<<<<<<< HEAD
>>>>>>> 822890f65bf73e8532339c88aa949a0c8de99c6b
=======
            url = new URL("http://10.40.27.8:8080/CONUNI_GR10/CONUNI?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CONUNI_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://10.40.27.8:8080/CONUNI_GR10/CONUNI?wsdl");
>>>>>>> 822890f65bf73e8532339c88aa949a0c8de99c6b
=======
            url = new URL("http://10.40.27.8:8080/CONUNI_GR10/CONUNI?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CONUNI_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://10.40.27.8:8080/CONUNI_GR10/CONUNI?wsdl");
>>>>>>> 822890f65bf73e8532339c88aa949a0c8de99c6b
=======
            url = new URL("http://10.40.27.8:8080/CONUNI_GR10/CONUNI?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CONUNI_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://10.40.27.8:8080/CONUNI_GR10/CONUNI?wsdl");
>>>>>>> 822890f65bf73e8532339c88aa949a0c8de99c6b
=======
            url = new URL("http://10.40.27.8:8080/CONUNI_GR10/CONUNI?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CONUNI_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://10.40.27.8:8080/CONUNI_GR10/CONUNI?wsdl");
>>>>>>> 822890f65bf73e8532339c88aa949a0c8de99c6b
=======
>>>>>>> 822890f65bf73e8532339c88aa949a0c8de99c6b
        }
        WSDL_LOCATION = url;
    }

    public CONUNI_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CONUNI_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CONUNI_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CONUNI_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CONUNI_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CONUNI_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CONUNI
     */
    @WebEndpoint(name = "CONUNIPort")
    public CONUNI getCONUNIPort() {
        return super.getPort(CONUNIPort, CONUNI.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CONUNI
     */
    @WebEndpoint(name = "CONUNIPort")
    public CONUNI getCONUNIPort(WebServiceFeature... features) {
        return super.getPort(CONUNIPort, CONUNI.class, features);
    }

}
