
package ec.edu.monster.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-05-05T00:14:43.484-05:00
 * Generated source version: 4.0.3
 *
 */
public final class CONUNI_CONUNIPort_Client {

    private static final QName SERVICE_NAME = new QName("http://controlador.monster.edu.ec/", "CONUNI");

    private CONUNI_CONUNIPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CONUNI_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        CONUNI_Service ss = new CONUNI_Service(wsdlURL, SERVICE_NAME);
        CONUNI port = ss.getCONUNIPort();

        {
        System.out.println("Invoking metrosAYardas...");
        double _metrosAYardas_metros = 0.0;
        double _metrosAYardas__return = port.metrosAYardas(_metrosAYardas_metros);
        System.out.println("metrosAYardas.result=" + _metrosAYardas__return);


        }
        {
        System.out.println("Invoking centimetrosAPulgadas...");
        double _centimetrosAPulgadas_centimetros = 0.0;
        double _centimetrosAPulgadas__return = port.centimetrosAPulgadas(_centimetrosAPulgadas_centimetros);
        System.out.println("centimetrosAPulgadas.result=" + _centimetrosAPulgadas__return);


        }
        {
        System.out.println("Invoking login...");
        java.lang.String _login_usuario = "";
        java.lang.String _login_contraseña = "";
        boolean _login__return = port.login(_login_usuario, _login_contraseña);
        System.out.println("login.result=" + _login__return);


        }
        {
        System.out.println("Invoking pulgadasACentimetros...");
        double _pulgadasACentimetros_pulgadas = 0.0;
        double _pulgadasACentimetros__return = port.pulgadasACentimetros(_pulgadasACentimetros_pulgadas);
        System.out.println("pulgadasACentimetros.result=" + _pulgadasACentimetros__return);


        }
        {
        System.out.println("Invoking metrosAPies...");
        double _metrosAPies_metros = 0.0;
        double _metrosAPies__return = port.metrosAPies(_metrosAPies_metros);
        System.out.println("metrosAPies.result=" + _metrosAPies__return);


        }
        {
        System.out.println("Invoking piesAMetros...");
        double _piesAMetros_pies = 0.0;
        double _piesAMetros__return = port.piesAMetros(_piesAMetros_pies);
        System.out.println("piesAMetros.result=" + _piesAMetros__return);


        }
        {
        System.out.println("Invoking yardasAMetros...");
        double _yardasAMetros_yardas = 0.0;
        double _yardasAMetros__return = port.yardasAMetros(_yardasAMetros_yardas);
        System.out.println("yardasAMetros.result=" + _yardasAMetros__return);


        }

        System.exit(0);
    }

}
