package ec.edu.monster.ws;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-05-13T13:24:55.061-05:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://controlador.monster.edu.ec/", name = "CONUNI")
@XmlSeeAlso({ObjectFactory.class})
public interface CONUNI {

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/CONUNI/metrosAYardasRequest", output = "http://controlador.monster.edu.ec/CONUNI/metrosAYardasResponse")
    @RequestWrapper(localName = "metrosAYardas", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.MetrosAYardas")
    @ResponseWrapper(localName = "metrosAYardasResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.MetrosAYardasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double metrosAYardas(

        @WebParam(name = "metros", targetNamespace = "")
        double metros
    );

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/CONUNI/centimetrosAPulgadasRequest", output = "http://controlador.monster.edu.ec/CONUNI/centimetrosAPulgadasResponse")
    @RequestWrapper(localName = "centimetrosAPulgadas", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.CentimetrosAPulgadas")
    @ResponseWrapper(localName = "centimetrosAPulgadasResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.CentimetrosAPulgadasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double centimetrosAPulgadas(

        @WebParam(name = "centimetros", targetNamespace = "")
        double centimetros
    );

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/CONUNI/pulgadasACentimetrosRequest", output = "http://controlador.monster.edu.ec/CONUNI/pulgadasACentimetrosResponse")
    @RequestWrapper(localName = "pulgadasACentimetros", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.PulgadasACentimetros")
    @ResponseWrapper(localName = "pulgadasACentimetrosResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.PulgadasACentimetrosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double pulgadasACentimetros(

        @WebParam(name = "pulgadas", targetNamespace = "")
        double pulgadas
    );

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/CONUNI/loginRequest", output = "http://controlador.monster.edu.ec/CONUNI/loginResponse")
    @RequestWrapper(localName = "login", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.LoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean login(

        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "contraseña", targetNamespace = "")
        java.lang.String contraseña
    );

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/CONUNI/metrosAPiesRequest", output = "http://controlador.monster.edu.ec/CONUNI/metrosAPiesResponse")
    @RequestWrapper(localName = "metrosAPies", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.MetrosAPies")
    @ResponseWrapper(localName = "metrosAPiesResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.MetrosAPiesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double metrosAPies(

        @WebParam(name = "metros", targetNamespace = "")
        double metros
    );

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/CONUNI/piesAMetrosRequest", output = "http://controlador.monster.edu.ec/CONUNI/piesAMetrosResponse")
    @RequestWrapper(localName = "piesAMetros", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.PiesAMetros")
    @ResponseWrapper(localName = "piesAMetrosResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.PiesAMetrosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double piesAMetros(

        @WebParam(name = "pies", targetNamespace = "")
        double pies
    );

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/CONUNI/yardasAMetrosRequest", output = "http://controlador.monster.edu.ec/CONUNI/yardasAMetrosResponse")
    @RequestWrapper(localName = "yardasAMetros", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.YardasAMetros")
    @ResponseWrapper(localName = "yardasAMetrosResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.YardasAMetrosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double yardasAMetros(

        @WebParam(name = "yardas", targetNamespace = "")
        double yardas
    );
}
