package ec.edu.monster.ws;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-05-25T20:24:56.904-05:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://controlador.monster.edu.ec/", name = "WSEureka")
@XmlSeeAlso({ObjectFactory.class})
public interface WSEureka {

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/WSEureka/iniciarSesionRequest", output = "http://controlador.monster.edu.ec/WSEureka/iniciarSesionResponse")
    @RequestWrapper(localName = "iniciarSesion", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.IniciarSesion")
    @ResponseWrapper(localName = "iniciarSesionResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.IniciarSesionResponse")
    @WebResult(name = "usuario", targetNamespace = "")
    public ec.edu.monster.ws.Usuario iniciarSesion(

        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "clave", targetNamespace = "")
        java.lang.String clave
    );

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/WSEureka/realizarTransferenciaRequest", output = "http://controlador.monster.edu.ec/WSEureka/realizarTransferenciaResponse")
    @RequestWrapper(localName = "realizarTransferencia", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.RealizarTransferencia")
    @ResponseWrapper(localName = "realizarTransferenciaResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.RealizarTransferenciaResponse")
    @WebResult(name = "estado", targetNamespace = "")
    public int realizarTransferencia(

        @WebParam(name = "cuentaOrigen", targetNamespace = "")
        java.lang.String cuentaOrigen,
        @WebParam(name = "cuentaDestino", targetNamespace = "")
        java.lang.String cuentaDestino,
        @WebParam(name = "importe", targetNamespace = "")
        double importe,
        @WebParam(name = "codEmp", targetNamespace = "")
        java.lang.String codEmp
    );

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/WSEureka/registrarDepositoRequest", output = "http://controlador.monster.edu.ec/WSEureka/registrarDepositoResponse")
    @RequestWrapper(localName = "registrarDeposito", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.RegistrarDeposito")
    @ResponseWrapper(localName = "registrarDepositoResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.RegistrarDepositoResponse")
    @WebResult(name = "estado", targetNamespace = "")
    public int registrarDeposito(

        @WebParam(name = "cuenta", targetNamespace = "")
        java.lang.String cuenta,
        @WebParam(name = "importe", targetNamespace = "")
        double importe,
        @WebParam(name = "codEmp", targetNamespace = "")
        java.lang.String codEmp
    );

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/WSEureka/obtenerCostoMovimientoRequest", output = "http://controlador.monster.edu.ec/WSEureka/obtenerCostoMovimientoResponse")
    @RequestWrapper(localName = "obtenerCostoMovimiento", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.ObtenerCostoMovimiento")
    @ResponseWrapper(localName = "obtenerCostoMovimientoResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.ObtenerCostoMovimientoResponse")
    @WebResult(name = "costo", targetNamespace = "")
    public double obtenerCostoMovimiento(

        @WebParam(name = "cuenta", targetNamespace = "")
        java.lang.String cuenta
    );

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/WSEureka/verificarSaldoRequest", output = "http://controlador.monster.edu.ec/WSEureka/verificarSaldoResponse")
    @RequestWrapper(localName = "verificarSaldo", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.VerificarSaldo")
    @ResponseWrapper(localName = "verificarSaldoResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.VerificarSaldoResponse")
    @WebResult(name = "saldo", targetNamespace = "")
    public double verificarSaldo(

        @WebParam(name = "cuenta", targetNamespace = "")
        java.lang.String cuenta
    );

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/WSEureka/registrarRetiroRequest", output = "http://controlador.monster.edu.ec/WSEureka/registrarRetiroResponse")
    @RequestWrapper(localName = "registrarRetiro", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.RegistrarRetiro")
    @ResponseWrapper(localName = "registrarRetiroResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.RegistrarRetiroResponse")
    @WebResult(name = "estado", targetNamespace = "")
    public int registrarRetiro(

        @WebParam(name = "cuenta", targetNamespace = "")
        java.lang.String cuenta,
        @WebParam(name = "importe", targetNamespace = "")
        double importe,
        @WebParam(name = "codEmp", targetNamespace = "")
        java.lang.String codEmp
    );

    @WebMethod
    @Action(input = "http://controlador.monster.edu.ec/WSEureka/leerMovimientosRequest", output = "http://controlador.monster.edu.ec/WSEureka/leerMovimientosResponse")
    @RequestWrapper(localName = "leerMovimientos", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.LeerMovimientos")
    @ResponseWrapper(localName = "leerMovimientosResponse", targetNamespace = "http://controlador.monster.edu.ec/", className = "ec.edu.monster.ws.LeerMovimientosResponse")
    @WebResult(name = "Movimiento", targetNamespace = "")
    public java.util.List<ec.edu.monster.ws.Movimiento> leerMovimientos(

        @WebParam(name = "cuenta", targetNamespace = "")
        java.lang.String cuenta
    );
}
