//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConversionServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConversionServiceReference.IConversionService")]
    public interface IConversionService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/pulgadasACentimetros", ReplyAction="http://tempuri.org/IConversionService/pulgadasACentimetrosResponse")]
        System.Threading.Tasks.Task<double> pulgadasACentimetrosAsync(double pulgadas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/centimetrosAPulgadas", ReplyAction="http://tempuri.org/IConversionService/centimetrosAPulgadasResponse")]
        System.Threading.Tasks.Task<double> centimetrosAPulgadasAsync(double centimetros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/metrosAPies", ReplyAction="http://tempuri.org/IConversionService/metrosAPiesResponse")]
        System.Threading.Tasks.Task<double> metrosAPiesAsync(double metros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/piesAMetros", ReplyAction="http://tempuri.org/IConversionService/piesAMetrosResponse")]
        System.Threading.Tasks.Task<double> piesAMetrosAsync(double pies);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/metrosAYardas", ReplyAction="http://tempuri.org/IConversionService/metrosAYardasResponse")]
        System.Threading.Tasks.Task<double> metrosAYardasAsync(double metros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/yardasAMetros", ReplyAction="http://tempuri.org/IConversionService/yardasAMetrosResponse")]
        System.Threading.Tasks.Task<double> yardasAMetrosAsync(double yardas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConversionService/Login", ReplyAction="http://tempuri.org/IConversionService/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string usuario, string contraseña);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IConversionServiceChannel : ConversionServiceReference.IConversionService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ConversionServiceClient : System.ServiceModel.ClientBase<ConversionServiceReference.IConversionService>, ConversionServiceReference.IConversionService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ConversionServiceClient() : 
                base(ConversionServiceClient.GetDefaultBinding(), ConversionServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IConversionService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConversionServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ConversionServiceClient.GetBindingForEndpoint(endpointConfiguration), ConversionServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConversionServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ConversionServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConversionServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ConversionServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConversionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<double> pulgadasACentimetrosAsync(double pulgadas)
        {
            return base.Channel.pulgadasACentimetrosAsync(pulgadas);
        }
        
        public System.Threading.Tasks.Task<double> centimetrosAPulgadasAsync(double centimetros)
        {
            return base.Channel.centimetrosAPulgadasAsync(centimetros);
        }
        
        public System.Threading.Tasks.Task<double> metrosAPiesAsync(double metros)
        {
            return base.Channel.metrosAPiesAsync(metros);
        }
        
        public System.Threading.Tasks.Task<double> piesAMetrosAsync(double pies)
        {
            return base.Channel.piesAMetrosAsync(pies);
        }
        
        public System.Threading.Tasks.Task<double> metrosAYardasAsync(double metros)
        {
            return base.Channel.metrosAYardasAsync(metros);
        }
        
        public System.Threading.Tasks.Task<double> yardasAMetrosAsync(double yardas)
        {
            return base.Channel.yardasAMetrosAsync(yardas);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string usuario, string contraseña)
        {
            return base.Channel.LoginAsync(usuario, contraseña);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IConversionService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IConversionService))
            {
                return new System.ServiceModel.EndpointAddress("http://10.40.17.133:8733/Design_Time_Addresses/ConversionUnidades_SOAP/Service1/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ConversionServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IConversionService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ConversionServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IConversionService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IConversionService,
        }
    }
}
