@ViajecitosRestServer_HostAddress = http://192.168.100.11:5158

# Buscar vuelos ordenados por precio (de mayor a menor)
GET {{ViajecitosRestServer_HostAddress}}/api/vuelos
Accept: application/json

###

# Iniciar sesión
POST {{ViajecitosRestServer_HostAddress}}/api/login?nombreUsuario=MONSTER&claveUsuario=MONSTER9
Content-Type: application/json
Accept: application/json

###

# Registrar un cliente
POST {{ViajecitosRestServer_HostAddress}}/api/cliente?nombre=Ana%20Torres&email=ana.torres@email.com&documentoIdentidad=1710474758
Content-Type: application/json
Accept: application/json

###



###

# Crear factura con detalles
POST {{ViajecitosRestServer_HostAddress}}/api/factura
Content-Type: application/json
Accept: application/json


###

# Obtener facturas de un cliente
GET {{ViajecitosRestServer_HostAddress}}/api/facturas/1
Accept: application/json


###

# Obtener todas las facturas organizadas por cliente
GET {{ViajecitosRestServer_HostAddress}}/api/facturas
Accept: application/json


###

# Obtener todos los clientes
GET {{ViajecitosRestServer_HostAddress}}/api/clientes
Accept: application/json


